name: persistent_bottom_nav_bar
description: A DO ALL persistent/static bottom navigation bar for flutter. In addition to being optionally platform specific, it includes more than 10 styles including neumorphic design.

homepage: https://github.com/BilalShahid13/PersistentBottomNavBar
repository: https://github.com/BilalShahid13/PersistentBottomNavBar
version: 1.5.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
